### PR TITLE
Increase gas limit and fix mnemonic for ganache

### PR DESCRIPTION
**Pull request by bingen**

### CODE REVIEW

**Comment by lacabra** [comment]
Hi @bingen, thanks for your PR. I regard the suggested changes as customizations that may help in your setup, but I don't necessarily regard them as improvements in the general case, so unless you want to make a strong argument for them, I will close this PR without merging.

In my opinion these are adaptations that perfectly fit your clone of this repo, but I don't necessarily see how they generalize to other use cases. Feel free to bring forward your arguments, and reopen this PR to continue the conversation.

(cc: @apalepu23)

**Comment by bingen** [comment]
Well, I disagree, but it's fine, it's your repo and so far I only needed it to help @apalepu23 set up the Enigma - Aragon voting app, which indeed I can do with my fork (I'm afraid it will be more inconvenient for him).
- About the mnemonic, I think it's useful for testing to have a deterministic environment, to be able to reproduce tests and errors easily, although I could imagine scenarios where the opposite may be helpful too.
- About the gas limit, I don't see the point of having the default low value, lower than actual mainnet one, which prevents valid apps from working.

Just curious, which are the downsides to these modifications?

**Comment by lacabra** [comment]
Both fair points, thanks for continuing the conversation.

For some downsides to a deterministic mnemonic, see this thread: https://github.com/trufflesuite/ganache/issues/275

You can always refer to any of the ganache/truffle accounts consistently by using something like:
```
let accounts;
web3.eth.getAccounts().then((result) => {
      accounts = result;
 });
// use accounts[0], accounts[1],... consistently in your tests
```
which to me is almost like having a deterministic mnemonic, but with the advantage that you ensure that you do not hardcode any such values in your code, and it will run fine once deployed on mainnet without being inadvertently dependent to certain addresses.

As per [Ganache's documentation](https://github.com/trufflesuite/ganache-cli/blob/master/README.md#using-ganache-cli), the default block gas limit is set to `0x6691b7` which equals `6721975`. On the other hand, [ethstats](https://ethstats.net) currently reports a block gas limit of around `8000000` (and seems to be somewhat stable over the past year [[1](https://medium.com/@piyopiyo/how-to-get-ethereum-block-gas-limit-eba2c8f32ce)]), which yes it is slightly higher but not almost an order of magnitude higher like the 50M you propose. It would make sense to bring it closer to the actual value, but why go so high? Isn't it unrealistically high?

**Comment by bingen** [comment]
Yes, as I said I can understand about the mnemonic, although for some use case it's also convenient to have it fixed (e.g. using accounts[0], "the owner", from outside), and I don't think people would loose funds for having it here, but anyway, not clear, so ok with leaving as it is.
About the gas, I just put it that high to forget about it "forever", but it's true that it would make sense to set it to a value closer to real one (although it probably will need to be changed after some time again). Let me know which one you want and I'll adapt it. Is 8M ok?
Thanks!

**Comment by lacabra** [comment]
No worries, I made the change myself to 8M and merged. Thanks!

**Pull request merged**
